include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] GPF 155mm"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_gpf155"
ENT.GunModel      = "models/gredwitch/gpf155/gpf155_gun.mdl"
ENT.GunPivotBone  = "gpf155_base"
ENT.GunMuzzleBone = "gpf155_barrel"
ENT.GunBarrelBone = ""
ENT.GunWeaponType = "rocket"
ENT.GunFireRate   = 0.033
ENT.GunDamage     = 500
ENT.GunYawMin     = -30
ENT.GunYawMax     = 30
ENT.GunPitchMin   = 5
ENT.GunPitchMax   = 65
ENT.GunTurnSpeed  = 15
ENT.GunMaxHealth  = 1000
ENT.GunRadius     = 6000
ENT.GunShootSound = "gred_emp/gpf155/gpf155_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(55, 0, 45)
