ENT.Base = "sentry_base"
ENT.PrintName = "M777 155mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_m777.png"

ENT.SentryModel   = "models/gredwitch/m777.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 500
ENT.RocketRadius  = 600
ENT.FireInterval  = 60 / 3
ENT.YawMin        = -45
ENT.YawMax        =  45
ENT.PitchMin      = -3
ENT.PitchMax      =  35
ENT.SentryHealth  = 800
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(80, 0, 12)
