include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] Bren"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_bren"
ENT.GunModel      = "models/gredwitch/bren/bren_gun.mdl"
ENT.GunPivotBone  = "bren_base"
ENT.GunMuzzleBone = "bren_barrel"
ENT.GunBarrelBone = "bren_barrels"
ENT.GunWeaponType = "hitscan"
ENT.GunFireRate   = 8.3
ENT.GunDamage     = 16
ENT.GunYawMin     = -180
ENT.GunYawMax     = 180
ENT.GunPitchMin   = -10
ENT.GunPitchMax   = 45
ENT.GunTurnSpeed  = 75
ENT.GunMaxHealth  = 250
ENT.GunRadius     = 1800
ENT.GunShootSound = "gred_emp/bren/bren_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(18, 0, 35)
