ENT.Base = "sentry_base"
ENT.PrintName = "Artemis 30mm AA Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_artemis30.png"

ENT.SentryModel      = "models/gredwitch/artemis30.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 55
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.012
ENT.BulletSound      = "weapons/emplacement/gun_shoot1.wav"
ENT.FireInterval     = 60 / 225
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -5
ENT.PitchMax         =  85
ENT.SentryHealth     = 650
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(50, 0, 16)
