ENT.Base = "sentry_base"
ENT.PrintName = "ZiS-2 57mm AT Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_zis2.png"

ENT.SentryModel   = "models/gredwitch/zis2.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 190
ENT.RocketRadius  = 140
ENT.FireInterval  = 60 / 12
ENT.YawMin        = -45
ENT.YawMax        =  45
ENT.PitchMin      = -5
ENT.PitchMax      =  15
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(60, 0, 10)
