ENT.Base = "sentry_base"
ENT.PrintName = "M2A1 105mm Howitzer Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_m2a1.png"

ENT.SentryModel   = "models/gredwitch/m2a1.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 350
ENT.RocketRadius  = 400
ENT.FireInterval  = 60 / 3.5
ENT.YawMin        = -45
ENT.YawMax        =  45
ENT.PitchMin      = -5
ENT.PitchMax      =  35
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(65, 0, 12)
