include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] FN MAG"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_fnmag"
ENT.GunModel      = "models/gredwitch/fnmag/fnmag_gun.mdl"
ENT.GunPivotBone  = "fnmag_base"
ENT.GunMuzzleBone = "fnmag_barrel"
ENT.GunBarrelBone = "fnmag_barrels"
ENT.GunWeaponType = "hitscan"
ENT.GunFireRate   = 13.3
ENT.GunDamage     = 18
ENT.GunYawMin     = -180
ENT.GunYawMax     = 180
ENT.GunPitchMin   = -15
ENT.GunPitchMax   = 45
ENT.GunTurnSpeed  = 75
ENT.GunMaxHealth  = 350
ENT.GunRadius     = 2000
ENT.GunShootSound = "gred_emp/fnmag/fnmag_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(20, 0, 38)
