ENT.Base = "sentry_base"
ENT.PrintName = "M2 Low-Mount .50 Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_m2_low.png"

ENT.SentryModel      = "models/gredwitch/m2_low.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 35
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.015
ENT.BulletSound      = "weapons/emplacement/gun_shoot1.wav"
ENT.FireInterval     = 60 / 525
ENT.YawMin           = -90
ENT.YawMax           =  90
ENT.PitchMin         = -5
ENT.PitchMax         =  20
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(42, 0, 10)
