ENT.Base = "sentry_base"
ENT.PrintName = "MG81Z Twin 7.92mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_mg81z.png"

ENT.SentryModel      = "models/gredwitch/mg81z.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 13
ENT.BulletNum        = 2
ENT.BulletInaccuracy = 0.02
ENT.BulletSound      = "weapons/ar2/fire1.wav"
ENT.FireInterval     = 60 / 1700
ENT.YawMin           = -90
ENT.YawMax           =  90
ENT.PitchMin         = -10
ENT.PitchMax         =  75
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(36, 0, 12)
