ENT.Base = "sentry_base"
ENT.PrintName = "Nebelwerfer 41 Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_nebelwerfer.png"

ENT.SentryModel   = "models/gredwitch/nebelwerfer.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 200
ENT.RocketRadius  = 350
ENT.FireInterval  = 60 / 8     -- 8 shots/min
ENT.YawMin        = -180
ENT.YawMax        =  180
ENT.PitchMin      = -5
ENT.PitchMax      =  45
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(40, 0, 10)
