include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] KwK AT"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_kwk"
ENT.GunModel      = "models/gredwitch/kwk/kwk_gun.mdl"
ENT.GunPivotBone  = "kwk_base"
ENT.GunMuzzleBone = "kwk_barrel"
ENT.GunBarrelBone = ""
ENT.GunWeaponType = "rocket"
ENT.GunFireRate   = 0.13
ENT.GunDamage     = 280
ENT.GunYawMin     = -30
ENT.GunYawMax     = 30
ENT.GunPitchMin   = -5
ENT.GunPitchMax   = 20
ENT.GunTurnSpeed  = 28
ENT.GunMaxHealth  = 700
ENT.GunRadius     = 4000
ENT.GunShootSound = "gred_emp/kwk/kwk_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(40, 0, 30)
