ENT.Base = "sentry_base"
ENT.PrintName = "Flak 40 128mm AA Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_flak40z.png"

ENT.SentryModel      = "models/gredwitch/flak40z.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 200
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.006
ENT.BulletSound      = "weapons/emplacement/gun_shoot1.wav"
ENT.FireInterval     = 60 / 10
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -3
ENT.PitchMax         =  85
ENT.SentryHealth     = 1200
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(80, 0, 24)
