include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] GAU-19"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_gau19"
ENT.GunModel      = "models/gredwitch/gau19/gau19_gun.mdl"
ENT.GunPivotBone  = "gau19_base"
ENT.GunMuzzleBone = "gau19_barrel"
ENT.GunBarrelBone = "gau19_barrels"
ENT.GunWeaponType = "hitscan"
ENT.GunFireRate   = 21.7
ENT.GunDamage     = 22
ENT.GunYawMin     = -180
ENT.GunYawMax     = 180
ENT.GunPitchMin   = -20
ENT.GunPitchMax   = 45
ENT.GunTurnSpeed  = 80
ENT.GunMaxHealth  = 400
ENT.GunRadius     = 2200
ENT.GunShootSound = "gred_emp/gau19/gau19_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(22, 0, 40)
