ENT.Base = "sentry_base"
ENT.PrintName = "PaK 38 AT Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_pak38.png"

ENT.SentryModel   = "models/gredwitch/pak38.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 180
ENT.RocketRadius  = 150
ENT.FireInterval  = 60 / 13
ENT.YawMin        = -45
ENT.YawMax        =  45
ENT.PitchMin      = -5
ENT.PitchMax      =  15
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(60, 0, 10)
