ENT.Base = "sentry_base"
ENT.PrintName = "leFH 18 105mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_lefh18.png"

ENT.SentryModel   = "models/gredwitch/lefh18.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 360
ENT.RocketRadius  = 420
ENT.FireInterval  = 60 / 5
ENT.YawMin        = -45
ENT.YawMax        =  45
ENT.PitchMin      = -6
ENT.PitchMax      =  45
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(68, 0, 12)
