ENT.Base = "sentry_base"
ENT.PrintName = "ZPU-4 1931 AA Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_zpu4_1931.png"

ENT.SentryModel      = "models/gredwitch/zpu4_1931.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 30
ENT.BulletNum        = 4
ENT.BulletInaccuracy = 0.018
ENT.BulletSound      = "weapons/emplacement/gun_shoot1.wav"
ENT.FireInterval     = 60 / 600
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -5
ENT.PitchMax         =  85
ENT.SentryHealth     = 550
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(44, 0, 14)
