ENT.Base = "sentry_base"
ENT.PrintName = "Phalanx CIWS Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_phalanx.png"
ENT.BoneBarrels = "barrels"

ENT.SentryModel      = "models/gredwitch/phalanx.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 20
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.018
ENT.BulletSound      = "weapons/ar2/fire1.wav"
ENT.FireInterval     = 60 / 3750
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -10
ENT.PitchMax         =  80
ENT.SentryHealth     = 700
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(44, 0, 16)
