ENT.Base = "sentry_base"
ENT.PrintName = "MG34 7.92mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_mg34.png"

ENT.SentryModel      = "models/gredwitch/mg34.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 14
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.02
ENT.BulletSound      = "weapons/ar2/fire1.wav"
ENT.FireInterval     = 60 / 850
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -10
ENT.PitchMax         =  45
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(38, 0, 10)
