ENT.Base = "sentry_base"
ENT.PrintName = "PM-41 Mortar Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_pm41.png"

ENT.SentryModel   = "models/gredwitch/pm41.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 110
ENT.RocketRadius  = 230
ENT.FireInterval  = 60 / 17
ENT.YawMin        = -180
ENT.YawMax        =  180
ENT.PitchMin      =  45
ENT.PitchMax      =  85
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(10, 0, 20)
