ENT.Base = "sentry_base"
ENT.PrintName = "Bren .303 Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_bren.png"

ENT.SentryModel      = "models/gredwitch/bren.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 15
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.022
ENT.BulletSound      = "weapons/ar2/fire1.wav"
ENT.FireInterval     = 60 / 510
ENT.YawMin           = -90
ENT.YawMax           =  90
ENT.PitchMin         = -10
ENT.PitchMax         =  45
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(36, 0, 10)
