ENT.Base = "sentry_base"
ENT.PrintName = "Breda 35mm AA Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_breda35.png"

ENT.SentryModel      = "models/gredwitch/breda35.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 28
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.018
ENT.BulletSound      = "weapons/emplacement/gun_shoot1.wav"
ENT.FireInterval     = 60 / 350
ENT.YawMin           = -60
ENT.YawMax           =  60
ENT.PitchMin         = -10
ENT.PitchMax         =  60
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(40, 0, 14)
