ENT.Base = "sentry_base"
ENT.PrintName = "M134 Minigun Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_m134.png"
ENT.BoneBarrels = "barrels"

ENT.SentryModel      = "models/gredwitch/m134.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 12
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.03
ENT.BulletSound      = "weapons/ar2/fire1.wav"
ENT.FireInterval     = 60 / 4000
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -10
ENT.PitchMax         =  50
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(38, 0, 12)
