ENT.Base = "sentry_base"
ENT.PrintName = "M240B 7.62mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_m240b.png"

ENT.SentryModel      = "models/gredwitch/m240b.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 18
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.02
ENT.BulletSound      = "weapons/ar2/fire1.wav"
ENT.FireInterval     = 60 / 800
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -10
ENT.PitchMax         =  50
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(40, 0, 12)
