ENT.Base = "sentry_base"
ENT.PrintName = "RPK 7.62mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_rpk.png"

ENT.SentryModel      = "models/gredwitch/rpk.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 15
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.025
ENT.BulletSound      = "weapons/ar2/fire1.wav"
ENT.FireInterval     = 60 / 600
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -10
ENT.PitchMax         =  45
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(36, 0, 10)
