include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] Flakvierling 38"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_flakvierling38"
ENT.GunModel      = "models/gredwitch/flakvierling38/flakvierling38_gun.mdl"
ENT.GunPivotBone  = "flakvierling_base"
ENT.GunMuzzleBone = "flakvierling_barrel"
ENT.GunBarrelBone = "flakvierling_barrels"
ENT.GunWeaponType = "hitscan"
ENT.GunFireRate   = 28.0
ENT.GunDamage     = 30
ENT.GunYawMin     = -180
ENT.GunYawMax     = 180
ENT.GunPitchMin   = -5
ENT.GunPitchMax   = 90
ENT.GunTurnSpeed  = 65
ENT.GunMaxHealth  = 600
ENT.GunRadius     = 3000
ENT.GunShootSound = "gred_emp/flakvierling38/flak38_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(28, 0, 50)
