ENT.Base = "sentry_base"
ENT.PrintName = "Kord 12.7mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_kord.png"

ENT.SentryModel      = "models/gredwitch/kord.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 33
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.014
ENT.BulletSound      = "weapons/emplacement/gun_shoot1.wav"
ENT.FireInterval     = 60 / 700
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -10
ENT.PitchMax         =  50
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(42, 0, 14)
