ENT.Base = "sentry_base"
ENT.PrintName = "Flak 38 20mm AA Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_flak38.png"

ENT.SentryModel      = "models/gredwitch/flak38.mdl"
ENT.FireType         = "BULLET"
ENT.BulletDamage     = 45
ENT.BulletNum        = 1
ENT.BulletInaccuracy = 0.014
ENT.BulletSound      = "weapons/emplacement/gun_shoot1.wav"
ENT.FireInterval     = 60 / 150
ENT.YawMin           = -180
ENT.YawMax           =  180
ENT.PitchMin         = -5
ENT.PitchMax         =  90
ENT.BoneYaw          = "base"
ENT.BonePitch        = "gun"
ENT.MuzzleFallback   = Vector(46, 0, 16)
