include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] Flak 36 88mm"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_flak36"
ENT.GunModel      = "models/gredwitch/flak36/flak36_gun.mdl"
ENT.GunPivotBone  = "flak36_base"
ENT.GunMuzzleBone = "flak36_barrel"
ENT.GunBarrelBone = "flak36_barrels"
ENT.GunWeaponType = "hitscan"
ENT.GunFireRate   = 0.25
ENT.GunDamage     = 120
ENT.GunYawMin     = -180
ENT.GunYawMax     = 180
ENT.GunPitchMin   = -3
ENT.GunPitchMax   = 85
ENT.GunTurnSpeed  = 35
ENT.GunMaxHealth  = 800
ENT.GunRadius     = 4000
ENT.GunShootSound = "gred_emp/flak36/flak36_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(40, 0, 60)
