ENT.Base = "sentry_base"
ENT.PrintName = "PaK 43 88mm Sentry"
ENT.Author = "kebinresi"
ENT.Category = "Combine Sentries"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.SpawnIcon = "entities/gred_emp_pak43.png"

ENT.SentryModel   = "models/gredwitch/pak43.mdl"
ENT.FireType      = "ROCKET"
ENT.RocketDamage  = 300
ENT.RocketRadius  = 180
ENT.FireInterval  = 60 / 8
ENT.YawMin        = -45
ENT.YawMax        =  45
ENT.PitchMin      = -5
ENT.PitchMax      =  15
ENT.BoneYaw       = "base"
ENT.BonePitch     = "gun"
ENT.MuzzleFallback = Vector(70, 0, 10)
