include("shared.lua")
ENT.Base           = "nachin_sentry_base"
ENT.PrintName      = "[SENTRY] Flak 40Z"
ENT.Author         = "kebinresi"
ENT.Category       = "Nachin Sentries"
ENT.Spawnable      = true
ENT.AdminSpawnable = true
ENT.SpawnMenuIcon  = "vgui/entities/gred_emp_flak40z"
ENT.GunModel      = "models/gredwitch/flak40z/flak40z_gun.mdl"
ENT.GunPivotBone  = "flak40z_base"
ENT.GunMuzzleBone = "flak40z_barrel"
ENT.GunBarrelBone = "flak40z_barrels"
ENT.GunWeaponType = "hitscan"
ENT.GunFireRate   = 0.83
ENT.GunDamage     = 150
ENT.GunYawMin     = -180
ENT.GunYawMax     = 180
ENT.GunPitchMin   = -3
ENT.GunPitchMax   = 90
ENT.GunTurnSpeed  = 30
ENT.GunMaxHealth  = 900
ENT.GunRadius     = 4500
ENT.GunShootSound = "gred_emp/flak40z/flak40z_shoot.wav"
ENT.GunMuzzleFX   = "MuzzleEffect"
ENT.GunMuzzleFB   = Vector(45, 0, 65)
